(function () {
  'use strict';

  var MAX_FILE_BYTES = 8 * 1024 * 1024;
  var CHUNK_BYTES = 8 * 1024;
  var state = { running: false, peers: {}, messages: [], transfers: {}, seen: {}, listeners: false, relay: false, recording: null, recorder: null, diagnostic: null, peerTest: null, startError: '', ecoTimer: null };
  var deviceId = localStorage.getItem('rw_mesh_device_id') || id();
  localStorage.setItem('rw_mesh_device_id', deviceId);

  function plugin() { return window.Capacitor && window.Capacitor.Plugins && window.Capacitor.Plugins.NearbyMesh; }
  function esc(value) { var d = document.createElement('div'); d.textContent = String(value == null ? '' : value); return d.innerHTML; }
  function id() { return Date.now().toString(36) + Math.random().toString(36).slice(2, 8); }
  function now() { return new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); }
  function requirePlugin() { var p = plugin(); if (!p) throw new Error('Trail Mesh is available only in the RoamWise Android app.'); return p; }
  function packet(type, data) { var p={ rw: 1, type: type, id: id(), origin: deviceId, ttl: state.relay ? 3 : 0, at: Date.now(), data: data || {} }; state.seen[p.id]=p.at; return JSON.stringify(p); }
  function sendPacket(type, data, endpointId) { return requirePlugin().sendMessage({ message: packet(type, data), endpointId: endpointId || null }); }
  function relayPacket(p, sourceEndpoint) { if(!state.relay || !p.ttl || p.ttl<1 || p.origin===deviceId || /^(file-|ping$|pong$)/.test(p.type)) return; var relayed=JSON.stringify(Object.assign({},p,{ttl:p.ttl-1})); Object.keys(state.peers).forEach(function(key){if(key!==sourceEndpoint&&state.peers[key].connected)requirePlugin().sendMessage({message:relayed,endpointId:key}).catch(function(){});}); }
  function toast(message) { if (typeof window.showToast === 'function') window.showToast(message); else alert(message); }
  function formatBytes(n) { return n < 1024 * 1024 ? Math.ceil(n / 1024) + ' KB' : (n / 1024 / 1024).toFixed(1) + ' MB'; }
  function peerCount() { return Object.keys(state.peers).filter(function (key) { return state.peers[key].connected; }).length; }
  function safeName() { return (localStorage.getItem('rw_mesh_name') || localStorage.getItem('rw_user_name') || 'RoamWise trekker').slice(0, 32); }
  function cue(kind) { if (localStorage.getItem('rw_audio_enabled')==='0') return; try { var C=window.AudioContext||window.webkitAudioContext;if(!C)return;var c=new C(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=kind==='alert'?740:kind==='success'?520:330;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(kind==='alert'?.11:.045,c.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+(kind==='alert'?.55:.16));o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+(kind==='alert'?.56:.17));o.onended=function(){c.close();}; } catch (_) {} }
  function scene(title,subtitle,icon) { return '<div class="rwm-scene" aria-label="'+esc(title)+'"><div class="rwm-sun"></div><div class="rwm-peak back"></div><div class="rwm-peak front"></div><div class="rwm-path"></div><div class="rwm-scene-copy"><span>'+icon+'</span><div><b>'+esc(title)+'</b><small>'+esc(subtitle)+'</small></div></div></div>'; }

  function styles() {
    if (document.getElementById('rwMeshStyles')) return;
    var s = document.createElement('style'); s.id = 'rwMeshStyles';
    s.textContent = '#rwMeshOverlay{position:fixed;inset:0;background:var(--bg,#07090F);z-index:2147483000;color:var(--t1,#F2EFE6);font-family:inherit;overflow:auto;overscroll-behavior:contain;padding-top:env(safe-area-inset-top);padding-bottom:env(safe-area-inset-bottom)}' +
      '.rwm-shell{max-width:720px;margin:auto;min-height:calc(100dvh - env(safe-area-inset-top) - env(safe-area-inset-bottom));background:radial-gradient(circle at 85% 0,rgba(142,79,255,.13),transparent 38%),var(--bg,#07090F)}.rwm-head{position:sticky;top:0;background:rgba(7,9,15,.94);backdrop-filter:blur(18px);padding:12px 16px;min-height:58px;box-sizing:border-box;display:flex;align-items:center;gap:10px;z-index:4;border-bottom:1px solid var(--b2,#26304C)}' +
      '.rwm-brand{width:36px;height:36px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,var(--gold,#E8BA6C),#A96CFF);box-shadow:0 0 24px rgba(169,108,255,.25)}.rwm-head h2{margin:0;flex:1;font-size:19px;letter-spacing:-.02em}.rwm-close,.rwm-btn{border:1px solid transparent;border-radius:12px;padding:11px 14px;font:700 13px/1 inherit;background:linear-gradient(135deg,var(--gold,#E8BA6C),var(--gold2,#C8913E));color:#08090F;min-height:42px}.rwm-close{width:42px;padding:0;font-size:20px}.rwm-btn.secondary{background:var(--bg2,#12151F);border-color:var(--b2,#26304C);color:var(--t1,#F2EFE6)}.rwm-btn.danger{background:linear-gradient(135deg,#FF746A,#C4302B);color:#fff}' +
      '.rwm-tabs{display:flex;overflow-x:auto;scrollbar-width:none;padding:10px 14px;gap:7px;background:rgba(7,9,15,.96);position:sticky;top:58px;z-index:3;border-bottom:1px solid var(--b2,#26304C)}.rwm-tabs::-webkit-scrollbar{display:none}.rwm-tab{white-space:nowrap;border:1px solid var(--b2,#26304C);border-radius:999px;padding:9px 13px;background:var(--bg2,#12151F);color:var(--t2,#A7ADBD);font:700 12px/1 inherit}.rwm-tab.active{background:linear-gradient(135deg,rgba(232,186,108,.18),rgba(169,108,255,.2));border-color:var(--gold,#E8BA6C);color:var(--gold,#E8BA6C)}' +
      '.rwm-body{padding:14px 14px calc(28px + env(safe-area-inset-bottom))}.rwm-panel{display:none}.rwm-panel.active{display:block}.rwm-card{background:linear-gradient(145deg,rgba(19,26,46,.98),rgba(12,16,30,.98));border:1px solid var(--b2,#26304C);border-radius:20px;padding:16px;margin-bottom:13px;box-shadow:0 16px 42px rgba(0,0,0,.2)}.rwm-card h3{margin:0 0 9px;font-size:17px}.rwm-note{font-size:12.5px;color:var(--t2,#A7ADBD);line-height:1.58}.rwm-note b{color:var(--t1,#F2EFE6)}.rwm-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.rwm-input{box-sizing:border-box;width:100%;background:var(--bg,#07090F);border:1px solid var(--b2,#26304C);border-radius:13px;padding:12px;color:var(--t1,#F2EFE6);margin:7px 0;font:inherit}' +
      '.rwm-msg{padding:10px 12px;border-radius:13px;background:var(--bg2,#12151F);border:1px solid var(--b2,#26304C);margin:7px 0}.rwm-msg.mine{background:rgba(232,186,108,.1);border-color:rgba(232,186,108,.35);margin-left:12%}.rwm-meta{font-size:10px;color:var(--t3,#747C91);margin-top:3px}.rwm-badge{font-size:10px;border-radius:999px;padding:5px 8px;background:var(--bg2,#12151F);border:1px solid var(--b2,#26304C)}.rwm-good{color:#4ADE80;border-color:rgba(74,222,128,.35)}.rwm-warn{color:var(--gold,#E8BA6C)}.rwm-sos{border-color:rgba(255,107,107,.55);background:linear-gradient(145deg,rgba(60,19,27,.96),rgba(20,16,28,.98))}.rwm-guide li{margin:8px 0;line-height:1.45}.rwm-progress{height:6px;background:#07090F;border-radius:5px;overflow:hidden}.rwm-progress i{display:block;height:100%;background:linear-gradient(90deg,var(--gold,#E8BA6C),#A96CFF)}' +
      '.rwm-test{display:grid;gap:7px;margin-top:10px}.rwm-check{display:flex;gap:8px;align-items:flex-start;padding:9px 10px;border-radius:11px;background:rgba(255,255,255,.035);font-size:12px}.rwm-check.pass{color:#4ADE80}.rwm-check.fail{color:#FF746A}.rwm-check.wait{color:var(--gold,#E8BA6C)}.rwm-error{display:none;margin-top:10px;padding:12px;border-radius:13px;background:rgba(255,83,83,.1);border:1px solid rgba(255,116,106,.45);color:#FFD4D0}.rwm-error.show{display:block}.rwm-scene{height:132px;position:relative;overflow:hidden;border-radius:20px;margin-bottom:13px;background:linear-gradient(160deg,#20294a 0%,#6b3d89 52%,#e8ba6c 130%);box-shadow:0 18px 46px #0008}.rwm-sun{position:absolute;width:44px;height:44px;border-radius:50%;right:15%;top:18px;background:#ffd487;box-shadow:0 0 30px #ffd48799;animation:rwmBreathe 4s ease-in-out infinite}.rwm-peak{position:absolute;left:-8%;bottom:-2px;width:75%;height:78%;background:#1b2440;clip-path:polygon(0 100%,45% 10%,58% 44%,68% 31%,100% 100%)}.rwm-peak.front{left:37%;width:76%;height:68%;background:#0d1428}.rwm-path{position:absolute;bottom:-20px;left:45%;width:28px;height:90px;background:#d8af6d;transform:perspective(80px) rotateX(28deg);border-radius:50%}.rwm-scene-copy{position:absolute;inset:auto 13px 12px;display:flex;gap:10px;align-items:center;padding:9px 11px;background:#080a12bf;border:1px solid #ffffff22;border-radius:14px;backdrop-filter:blur(9px)}.rwm-scene-copy>span{font-size:24px}.rwm-scene-copy b,.rwm-scene-copy small{display:block}.rwm-scene-copy small{font-size:10px;color:#bdc3d2;margin-top:2px}.rwm-tip{border-left:3px solid var(--gold,#E8BA6C);padding-left:10px}.rwm-choice{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.rwm-choice .rwm-btn{min-height:54px}#rwMeshFab{position:fixed;right:14px;bottom:calc(108px + env(safe-area-inset-bottom));z-index:99999;width:48px;height:48px;border:1px solid rgba(232,186,108,.5);border-radius:16px;background:linear-gradient(135deg,#171D31,#2A1740);color:var(--gold,#E8BA6C);font-size:21px;box-shadow:0 12px 30px #0009}#rwMeshOverlay:not([style*="display: none"])~#rwMeshFab{display:none}.rwm-alarm{animation:rwmPulse .7s infinite alternate}@keyframes rwmPulse{to{background:#f00}}@keyframes rwmBreathe{50%{transform:scale(1.1);opacity:.82}}@media(prefers-reduced-motion:reduce){.rwm-sun,.rwm-alarm{animation:none}}@media(max-width:420px){.rwm-head{padding-left:12px;padding-right:12px}.rwm-body{padding-left:10px;padding-right:10px}.rwm-btn{flex:1}.rwm-tabs{padding-left:10px}}';
    document.head.appendChild(s);
  }

  function template() {
    return '<div class="rwm-shell"><div class="rwm-head"><span class="rwm-brand">📡</span><h2>Trail Mesh</h2><span id="rwmStatus" class="rwm-badge">Stopped</span><button class="rwm-close" data-rwm-close aria-label="Close Trail Mesh">✕</button></div>' +
      '<div class="rwm-tabs">' + ['Connect','Chat','Team','SOS','Share','Fun','Guide'].map(function (x, i) { return '<button class="rwm-tab '+(i?'':'active')+'" data-rwm-tab="'+x.toLowerCase()+'">'+x+'</button>'; }).join('') + '</div><div class="rwm-body">' +
      '<section class="rwm-panel active" data-rwm-panel="connect">'+scene('Your offline trail lifeline','Nearby phones · no internet required','🏔️')+'<div class="rwm-card"><h3>Before Trail Mesh starts</h3><p class="rwm-note"><b>RoamWise uses Nearby Devices access (Bluetooth and nearby Wi-Fi) to discover and communicate with verified RoamWise phones near you.</b> Your chosen trail name is visible nearby while Trail Mesh runs. Text and alerts are transferred device-to-device. Microphone, precise location and selected-file access occur only when you separately choose a voice note, location-assisted SOS or file share.</p><p class="rwm-note">Internet and mobile service are not required, but devices must remain within local radio range. Trail Mesh is not satellite rescue and does not replace emergency services.</p><input id="rwmName" class="rwm-input" maxlength="32" placeholder="Trail display name"><label class="rwm-note"><input id="rwmEco" type="checkbox" checked> Battery guard: stop automatically after 2 hours (recommended)</label><div class="rwm-row"><button id="rwmStart" class="rwm-btn">Allow & start</button><button id="rwmStop" class="rwm-btn secondary">Stop</button><button id="rwmPing" class="rwm-btn secondary">Test network</button></div><div id="rwmStartError" class="rwm-error" role="alert"></div></div><div class="rwm-card"><h3>Multi-hop relay (experimental)</h3><label><input id="rwmRelay" type="checkbox"> Relay text, team, lost-trekker and SOS alerts through verified phones</label><p class="rwm-note">Opt-in on each phone. Maximum three hops; duplicate IDs and expiry prevent loops. Files, songs, videos and voice notes are never relayed because they can congest an emergency network. Relay confirms forwarding—not rescue delivery.</p></div><div class="rwm-card"><h3>Nearby trekkers <span id="rwmPeerCount" class="rwm-badge">0</span></h3><div id="rwmPeers" class="rwm-note">No connected trekkers yet.</div></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="chat"><div class="rwm-card"><h3>Offline Trip Chat & radio room</h3><p class="rwm-note">Messages are shared with verified connected devices and can appear in Trip Chat. Voice is push-to-talk: record, release and share. This remains usable under weak links where live conferencing would break.</p><div id="rwmMessages"></div><textarea id="rwmChatInput" class="rwm-input" rows="2" maxlength="4000" placeholder="Message your nearby team"></textarea><div class="rwm-row"><button id="rwmSend" class="rwm-btn">Send offline</button><button id="rwmVoice" class="rwm-btn secondary">🎙 Hold radio note</button><button id="rwmRadioCheck" class="rwm-btn secondary">Radio check</button></div></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="team"><div class="rwm-card"><h3>Trek leader coordination</h3><input id="rwmCheckpoint" class="rwm-input" maxlength="120" placeholder="Checkpoint or meeting place"><div class="rwm-row"><button class="rwm-btn" data-rwm-team="rollcall">Roll call</button><button class="rwm-btn secondary" data-rwm-team="regroup">Regroup</button><button class="rwm-btn secondary" data-rwm-team="hold">Hold position</button></div></div><div class="rwm-card"><h3>Find a lost trekker</h3><p class="rwm-note">Broadcasts an alert locally. The missing person becomes discoverable only when their phone is running Trail Mesh and enters radio range.</p><input id="rwmLostName" class="rwm-input" maxlength="80" placeholder="Name / description"><button id="rwmLost" class="rwm-btn danger">Broadcast lost-trekker alert</button></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="sos"><div class="rwm-card rwm-sos"><h3>Emergency help</h3><p class="rwm-note">If mobile service exists, contact local emergency services first. Trail Mesh only alerts nearby connected users and delivery is not guaranteed.</p><select id="rwmSosType" class="rwm-input"><option>Medical emergency</option><option>Lost / separated</option><option>Unsafe situation</option><option>Need supplies or assistance</option></select><input id="rwmSosDetails" class="rwm-input" maxlength="240" placeholder="Details, clothing, direction, injury"><div class="rwm-row"><button id="rwmSOS" class="rwm-btn danger">Broadcast nearby SOS</button><button id="rwmAlarm" class="rwm-btn secondary">Sound local alarm</button><button id="rwmOfficialSOS" class="rwm-btn secondary">Open RoamWise SOS</button></div></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="share"><div class="rwm-card"><h3>Share without internet</h3><p class="rwm-note">Send a photo, short video, voice note, document, or song up to 8 MB to directly connected teammates. Keep the app open and devices nearby until complete.</p><input id="rwmFile" type="file" class="rwm-input" accept="image/*,video/*,audio/*,.pdf,.txt"><button id="rwmShare" class="rwm-btn">Share selected file</button><div id="rwmTransfers"></div></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="fun">'+scene('Camp mode','Tiny offline games, big trail memories','🔥')+'<div class="rwm-card"><h3>Trail fun</h3><p class="rwm-note">Lightweight activities designed not to flood the radio. Shared music and videos still use the Share tab.</p><div class="rwm-choice"><button class="rwm-btn" data-rwm-fun="photo">📷 Photo challenge</button><button class="rwm-btn secondary" data-rwm-fun="story">🔥 Campfire story</button><button class="rwm-btn secondary" data-rwm-fun="quiz">🧭 Trail quiz</button><button class="rwm-btn secondary" data-rwm-fun="cheer">🙌 Team cheer</button><button class="rwm-btn secondary" data-rwm-fun="scavenger">🍃 Scavenger hunt</button><button class="rwm-btn secondary" data-rwm-fun="summit">🏁 Summit countdown</button></div></div></section>' +
      '<section class="rwm-panel rwm-guide" data-rwm-panel="guide"><div class="rwm-card"><h3>Quick tutorial</h3><ol><li>Open Trail Mesh on every Android phone and tap <b>Allow & start</b>.</li><li>Keep Bluetooth, Wi-Fi and location services enabled. Android may require Nearby Devices and location permissions.</li><li>Compare the verification digits shown on both phones in person. Accept only when they match.</li><li>Use Offline Trip Chat, Team, Share, Fun, or SOS. Keep phones nearby and the app open during transfers.</li><li>Enable relay only when the group agrees; distribute relay phones along the route.</li><li>Tap Stop when the trek ends to stop discovery and advertising.</li></ol></div><div class="rwm-card"><h3>Safety & privacy</h3><ul><li>Your chosen trail name is visible to nearby Trail Mesh users while running.</li><li>Never accept an unexpected verification request.</li><li>Range varies with terrain, bodies, weather, and hardware. Relay is limited to three hops and lightweight alerts.</li><li>Voice uses recorded push-to-talk notes; it is not a guaranteed full-duplex phone call.</li><li>Use official emergency channels whenever available. Do not rely on Trail Mesh as your only safety plan.</li></ul></div><div class="rwm-card"><h3>Ailon Tusk shortcuts</h3><p class="rwm-note">Try: “open Trail Mesh”, “mesh status”, “find lost trekker”, or “nearby SOS”. Tusk opens the matching control while you confirm every safety-sensitive broadcast.</p></div></section></div></div>';
  }

  function decoratePanels(root) {
    var art={chat:['Trail radio room','Text and voice notes across the group','💬'],team:['Keep the line together','Roll calls, regrouping and lost-trekker alerts','🧭'],sos:['Help travels outward','Local alarm and verified nearby SOS relay','🆘'],share:['Pass memories phone to phone','Photos, songs and short videos without data','📸'],guide:['Ready before the trail','Practice together while mobile service still works','🥾']};
    Object.keys(art).forEach(function(name){var panel=root.querySelector('[data-rwm-panel="'+name+'"]');if(panel&&!panel.querySelector('.rwm-scene'))panel.insertAdjacentHTML('afterbegin',scene(art[name][0],art[name][1],art[name][2]));});
    var guide=root.querySelector('[data-rwm-panel="guide"]');
    if(guide&&!guide.querySelector('#rwmFeatureGuide'))guide.insertAdjacentHTML('beforeend','<div class="rwm-card" id="rwmFeatureGuide"><h3>Feature-by-feature field guide</h3><p class="rwm-note rwm-tip"><b>Connect:</b> Start on every phone before departure, compare verification digits face to face, then run the teammate test with airplane mode on and Bluetooth/Wi-Fi re-enabled.</p><p class="rwm-note rwm-tip"><b>Chat:</b> Use text for fast updates and short voice notes when gloves or darkness make typing difficult. Messages need at least one verified peer.</p><p class="rwm-note rwm-tip"><b>Team:</b> Set a checkpoint, run roll calls at junctions, and use Hold position before searching for a missing person.</p><p class="rwm-note rwm-tip"><b>SOS:</b> Describe injury, clothing and direction; add location only when requested. Sound the alarm to help nearby searchers, but call emergency services whenever possible.</p><p class="rwm-note rwm-tip"><b>Share:</b> Select one file under 8 MB and keep both screens open until complete. Prefer compressed media to preserve battery and radio capacity.</p><p class="rwm-note rwm-tip"><b>Fun:</b> Start a tiny challenge for the group. Activities send only text; use Share separately for the winning photo or song.</p><p class="rwm-note rwm-tip"><b>Battery:</b> Keep the two-hour guard on for casual use. Turn it off only for a planned long session, and stop Trail Mesh at camp or journey end.</p></div>');
  }

  function open(tab) {
    styles(); var overlay = document.getElementById('rwMeshOverlay');
    if (!overlay) { overlay = document.createElement('div'); overlay.id = 'rwMeshOverlay'; overlay.innerHTML = template(); document.body.appendChild(overlay); decoratePanels(overlay); installDiagnosticCard(overlay); bindUI(overlay); }
    overlay.style.display = 'block'; var fab=document.getElementById('rwMeshFab');if(fab)fab.style.display='none';document.body.style.overflow = 'hidden'; selectTab(tab || 'connect'); render();
  }
  function close() { var o = document.getElementById('rwMeshOverlay'); if (o) o.style.display = 'none'; var fab=document.getElementById('rwMeshFab');if(fab)fab.style.display='';document.body.style.overflow = ''; stopAlarm(); }
  function selectTab(name) { document.querySelectorAll('[data-rwm-tab]').forEach(function (x) { x.classList.toggle('active', x.dataset.rwmTab === name); }); document.querySelectorAll('[data-rwm-panel]').forEach(function (x) { x.classList.toggle('active', x.dataset.rwmPanel === name); }); }
  function render() {
    var status = document.getElementById('rwmStatus'); if (status) { status.textContent = state.running ? 'Running · ' + peerCount() + ' connected' : 'Stopped'; status.className = 'rwm-badge ' + (state.running ? 'rwm-good' : ''); }
    var pc = document.getElementById('rwmPeerCount'); if (pc) pc.textContent = String(peerCount());
    var peers = document.getElementById('rwmPeers'); if (peers) { var list = Object.keys(state.peers).map(function (key) { var p = state.peers[key]; return '<div class="rwm-msg"><b>'+esc(p.name || 'Nearby trekker')+'</b><div class="rwm-meta">'+esc(p.connected ? 'Connected and verified' : p.found ? 'Discovered' : 'Disconnected')+'</div></div>'; }); peers.innerHTML = list.join('') || 'No connected trekkers yet.'; }
    var messages = document.getElementById('rwmMessages'); if (messages) { messages.innerHTML = state.messages.slice(-100).map(function (m) { return '<div class="rwm-msg '+(m.mine?'mine':'')+'"><b>'+esc(m.from)+'</b> '+esc(m.text)+'<div class="rwm-meta">'+esc(m.time)+'</div></div>'; }).join('') || '<p class="rwm-note">No offline messages yet.</p>'; messages.scrollTop = messages.scrollHeight; }
    renderDiagnostic();
  }

  function installDiagnosticCard(root) {
    if (root.querySelector('#rwmSelfTest')) return;
    var panel=root.querySelector('[data-rwm-panel="connect"]'), card=document.createElement('div');
    card.className='rwm-card';
    card.innerHTML='<h3>Offline readiness test</h3><p class="rwm-note">Switch off mobile data and internet first. The one-phone check proves permissions and the local Nearby engine. The teammate test proves a real device-to-device message and reply.</p><div class="rwm-row"><button id="rwmSelfTest" class="rwm-btn">Run offline check</button><button id="rwmPeerTest" class="rwm-btn secondary">Test with teammate</button></div><div id="rwmTestResults" class="rwm-test"><div class="rwm-check wait">○ No test run yet</div></div>';
    panel.insertBefore(card,panel.lastElementChild);
    card.querySelector('#rwmSelfTest').onclick=runSelfTest;
    card.querySelector('#rwmPeerTest').onclick=runPeerTest;
  }
  function renderDiagnostic() {
    var el=document.getElementById('rwmTestResults'); if(!el)return;
    var d=state.diagnostic, rows=[];
    if(d){rows.push([d.native,'Native Trail Mesh bridge loaded']);rows.push([d.granted,'Nearby permissions granted']);rows.push([d.running,'Discovery and advertising running']);rows.push([d.offline,'Internet appears off (expected for blackout test)']);rows.push([d.topology,'P2P cluster radio topology ready']);}
    if(state.peerTest)rows.push([state.peerTest.pass,state.peerTest.text]);
    if(!rows.length)return;
    el.innerHTML=rows.map(function(r){var cls=r[0]===true?'pass':r[0]===false?'fail':'wait';return '<div class="rwm-check '+cls+'">'+(r[0]===true?'✓':r[0]===false?'✕':'…')+' '+esc(r[1])+'</div>';}).join('');
  }
  async function runSelfTest() {
    var d={native:Boolean(plugin()),granted:false,running:false,offline:navigator.onLine===false,topology:false};
    try{var s=await requirePlugin().getStatus();d.granted=Boolean(s.granted);d.running=Boolean(s.running);d.topology=s.topology==='P2P_CLUSTER';}catch(e){d.error=e.message;}
    state.diagnostic=d;renderDiagnostic();
    if(d.native&&d.granted&&d.running&&d.topology)toast(d.offline?'Offline readiness passed — now test with a teammate':'Radio engine ready. Switch off internet and rerun for blackout proof.');else toast('Offline readiness needs attention — review the failed checks.');
  }
  async function runPeerTest() {
    if(!state.running){state.peerTest={pass:false,text:'Start Trail Mesh before teammate test'};renderDiagnostic();return;}
    if(!peerCount()){state.peerTest={pass:false,text:'No verified teammate connected — start Trail Mesh on a second phone and match the verification digits'};renderDiagnostic();return;}
    var testId=id();state.transfers['ping:'+testId]=Date.now();state.peerTest={id:testId,pass:null,text:'Waiting up to 12 seconds for an offline reply…'};renderDiagnostic();
    try{await sendPacket('ping',{testId:testId,from:safeName()});}catch(e){state.peerTest={pass:false,text:'Could not send test: '+e.message};renderDiagnostic();return;}
    setTimeout(function(){if(state.peerTest&&state.peerTest.id===testId&&state.peerTest.pass===null){state.peerTest={pass:false,text:'No reply received — keep both apps open, nearby, verified, with Bluetooth and Wi-Fi enabled'};renderDiagnostic();}},12000);
  }

  function showStartError(message) { state.startError=message||'';var el=document.getElementById('rwmStartError');if(!el)return;el.classList.toggle('show',Boolean(message));el.innerHTML=message?'<b>Trail Mesh could not start</b><p>'+esc(message)+'</p><button id="rwmSettings" class="rwm-btn secondary">Open Android app settings</button><p class="rwm-note rwm-tip">Keep Bluetooth and Wi-Fi switched on, allow Nearby devices, then return and tap Allow & start again. This is local Android setup—not Firestore.</p>':'';var b=document.getElementById('rwmSettings');if(b)b.onclick=function(){requirePlugin().openAppSettings();}; }
  async function start() { try { showStartError('');var button=document.getElementById('rwmStart');button.disabled=true;button.textContent='Starting radios…';var name=document.getElementById('rwmName').value.trim()||safeName();localStorage.setItem('rw_mesh_name',name);await requirePlugin().requestMeshPermissions();await requirePlugin().start({displayName:name});state.running=true;if(state.ecoTimer)clearTimeout(state.ecoTimer);if(document.getElementById('rwmEco').checked)state.ecoTimer=setTimeout(function(){stop();toast('Trail Mesh stopped by the 2-hour battery guard');},7200000);render();cue('success');toast('Trail Mesh is running nearby'); } catch(e){var msg=e.message||'Could not start Trail Mesh';if(/8032|MISSING_PERMISSION/i.test(msg))msg='Android granted the visible prompt, but Google Nearby is missing a required Wi-Fi permission. Install this corrected build, then allow Nearby devices in App settings.';showStartError(msg);cue('alert');} finally {var b=document.getElementById('rwmStart');if(b){b.disabled=false;b.textContent='Allow & start';}} }
  async function stop() { try { await requirePlugin().stop();if(state.ecoTimer)clearTimeout(state.ecoTimer);state.ecoTimer=null;state.running=false;state.peers={};render();toast('Trail Mesh stopped'); } catch (e) { toast(e.message || 'Could not stop Trail Mesh'); } }
  async function sendChat(text, source) { text = String(text || '').trim(); if (!text) return; await sendPacket('chat', { text: text, source: source || 'mesh', from: safeName() }); state.messages.push({ mine: true, from: 'You', text: text, time: now() }); render(); }
  function mirrorToTripChat(message) { var box = document.querySelector('#groupChatMessages,.group-chat-messages,#tripChatMessages'); if (!box) return; var row = document.createElement('div'); row.className = 'chat-message mesh-message'; row.innerHTML = '<b>📡 '+esc(message.from || 'Nearby trekker')+'</b><div>'+esc(message.text)+'</div><small>Offline Trail Mesh · '+esc(now())+'</small>'; box.appendChild(row); }

  async function networkTest() { return runPeerTest(); }
  async function radioCheck() { await sendPacket('team',{action:'radio-check',text:'Radio check — reply SAFE with your name and position',from:safeName()}); state.messages.push({mine:true,from:'Radio room',text:'Radio check sent',time:now()}); render(); }
  async function fun(kind) { var prompts={photo:'Photo challenge: capture the best trail view in 10 minutes 📷',story:'Campfire round: share a two-minute travel story 🔥',quiz:'Trail quiz: leader, send the next nature or navigation question 🧭',cheer:'Team cheer from '+safeName()+' 🙌',scavenger:'Scavenger hunt: find a heart-shaped stone, three leaf colours, or an animal track 🍃',summit:'Summit countdown: share your ETA and one word for the final push 🏁'}; await sendPacket('fun',{kind:kind,text:prompts[kind],from:safeName()}); state.messages.push({mine:true,from:'Trail fun',text:prompts[kind],time:now()});render();cue('success'); }
  async function team(kind) { var cp = (document.getElementById('rwmCheckpoint').value || '').trim(); var labels = { rollcall: 'Roll call: reply that you are safe', regroup: 'Regroup' + (cp ? ' at '+cp : ' at the agreed checkpoint'), hold: 'Hold position and wait for the leader' }; await sendPacket('team', { action: kind, text: labels[kind], from: safeName() }); state.messages.push({ mine: true, from: 'Team command', text: labels[kind], time: now() }); render(); toast('Team command broadcast nearby'); }
  async function lost() { var name = document.getElementById('rwmLostName').value.trim(); if (!name) return toast('Add the lost trekker’s name or description'); if (!confirm('Broadcast this lost-trekker alert to all connected nearby devices?')) return; await sendPacket('lost', { person: name, from: safeName() }); toast('Lost-trekker alert broadcast nearby'); }
  async function getLocation() { try { var pos = await new Promise(function (resolve, reject) { navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 10000 }); }); return { lat: +pos.coords.latitude.toFixed(6), lng: +pos.coords.longitude.toFixed(6), accuracy: Math.round(pos.coords.accuracy) }; } catch (_) { return null; } }
  async function sos() { var type = document.getElementById('rwmSosType').value, details = document.getElementById('rwmSosDetails').value.trim(); if (!confirm('Broadcast a nearby SOS? Delivery is not guaranteed. Contact emergency services when possible.')) return; var location = await getLocation(); await sendPacket('sos', { emergency: type, details: details, location: location, from: safeName() }); startAlarm(); toast('SOS broadcast to connected nearby devices'); }
  var alarmCtx;
  function startAlarm() { stopAlarm(); var b = document.getElementById('rwmAlarm'); if (b) { b.classList.add('rwm-alarm'); b.textContent = 'Stop alarm'; } try { alarmCtx = new (window.AudioContext || window.webkitAudioContext)(); var o = alarmCtx.createOscillator(), g = alarmCtx.createGain(); o.frequency.value = 880; g.gain.value = .2; o.connect(g); g.connect(alarmCtx.destination); o.start(); alarmCtx.oscillator = o; } catch (_) {} if (navigator.vibrate) navigator.vibrate([500,250,500,250,1000]); }
  function stopAlarm() { if (alarmCtx) { try { alarmCtx.close(); } catch (_) {} alarmCtx = null; } if (navigator.vibrate) navigator.vibrate(0); var b = document.getElementById('rwmAlarm'); if (b) { b.classList.remove('rwm-alarm'); b.textContent = 'Sound local alarm'; } }

  function bytesToBase64(bytes) { var out = ''; for (var i=0;i<bytes.length;i++) out += String.fromCharCode(bytes[i]); return btoa(out); }
  function base64ToBytes(value) { var raw = atob(value), out = new Uint8Array(raw.length); for (var i=0;i<raw.length;i++) out[i] = raw.charCodeAt(i); return out; }
  async function shareFile(file) { if (!file) return toast('Choose a file first'); if (file.size > MAX_FILE_BYTES) return toast('Choose a file smaller than 8 MB'); if (!state.running || !peerCount()) return toast('Start Trail Mesh and connect a verified device first'); var transferId = id(), total = Math.ceil(file.size / CHUNK_BYTES); await sendPacket('file-start', { transferId: transferId, name: file.name, mime: file.type || 'application/octet-stream', size: file.size, total: total }); for (var i=0;i<total;i++) { var bytes = new Uint8Array(await file.slice(i*CHUNK_BYTES, (i+1)*CHUNK_BYTES).arrayBuffer()); await sendPacket('file-chunk', { transferId: transferId, index: i, value: bytesToBase64(bytes) }); updateTransfer('Sending '+file.name, (i+1)/total); } await sendPacket('file-end', { transferId: transferId }); toast('Shared '+file.name+' nearby'); }
  function updateTransfer(label, ratio, link) { var el = document.getElementById('rwmTransfers'); if (!el) return; el.innerHTML = '<div class="rwm-card"><div>'+esc(label)+'</div><div class="rwm-progress"><i style="width:'+Math.round(ratio*100)+'%"></i></div>'+(link || '')+'</div>' + el.innerHTML; }
  function receiveFile(p) { var d = p.data || {}, t = state.transfers[d.transferId]; if (p.type === 'file-start') { state.transfers[d.transferId] = { name: d.name, mime: d.mime, size: d.size, total: d.total, chunks: [] }; updateTransfer('Receiving '+d.name, 0); } else if (p.type === 'file-chunk' && t) { t.chunks[d.index] = base64ToBytes(d.value); updateTransfer('Receiving '+t.name, t.chunks.filter(Boolean).length/t.total); } else if (p.type === 'file-end' && t && t.chunks.filter(Boolean).length === t.total) { var url = URL.createObjectURL(new Blob(t.chunks, { type: t.mime })); updateTransfer('Received '+t.name+' · '+formatBytes(t.size), 1, '<p><a class="rwm-btn" download="'+esc(t.name)+'" href="'+url+'">Open / save</a></p>'); delete state.transfers[d.transferId]; toast('Received '+t.name); } }
  async function toggleVoice() { if (state.recorder && state.recorder.state === 'recording') { state.recorder.stop(); return; } try { var stream = await navigator.mediaDevices.getUserMedia({ audio: true }), chunks = []; state.recorder = new MediaRecorder(stream); state.recorder.ondataavailable = function (e) { if (e.data.size) chunks.push(e.data); }; state.recorder.onstop = function () { stream.getTracks().forEach(function (x) { x.stop(); }); var blob = new Blob(chunks, { type: state.recorder.mimeType || 'audio/webm' }); shareFile(new File([blob], 'trail-voice-'+Date.now()+'.webm', { type: blob.type })); state.recorder = null; var b=document.getElementById('rwmVoice'); if(b)b.textContent='🎙 Record voice note'; }; state.recorder.start(); var btn=document.getElementById('rwmVoice'); if(btn)btn.textContent='⏹ Send voice note'; setTimeout(function(){ if(state.recorder && state.recorder.state==='recording')state.recorder.stop(); },60000); } catch (e) { toast('Microphone access is required for voice notes'); } }

  function onPacket(event) { var p; try { p = JSON.parse(event.message); } catch (_) { p = { type:'chat', data:{ text:event.message, from:event.displayName } }; } if (!p || p.rw !== 1 && p.type !== 'chat') return; if(p.id&&state.seen[p.id])return; if(p.id){state.seen[p.id]=Date.now();Object.keys(state.seen).forEach(function(key){if(Date.now()-state.seen[key]>600000)delete state.seen[key];});} var d=p.data||{}; if (p.type==='chat') { var m={ mine:false, from:d.from||event.displayName||'Nearby trekker', text:d.text||'', time:now() }; state.messages.push(m); mirrorToTripChat(m); toast('Offline message from '+m.from); render(); } else if (p.type==='ping') { sendPacket('pong',{testId:d.testId,from:safeName()},event.endpointId); } else if (p.type==='pong') { var sent=state.transfers['ping:'+d.testId]; if(sent){ var latency=Date.now()-sent; state.peerTest={id:d.testId,pass:true,text:'Offline teammate reply received in '+latency+' ms — device-to-device messaging works'}; toast('Offline teammate test passed in '+latency+' ms'); delete state.transfers['ping:'+d.testId]; renderDiagnostic(); } } else if (p.type.indexOf('file-')===0) receiveFile(p); else if (p.type==='sos') { startAlarm(); open('sos'); toast('Nearby SOS from '+(d.from||'a trekker')+': '+(d.emergency||'Help needed')); } else if (p.type==='lost') { open('team'); toast('Lost-trekker alert: '+(d.person||'unknown person')); } else if (p.type==='team'||p.type==='fun') { state.messages.push({mine:false,from:(p.type==='fun'?'Trail fun':'Team')+' · '+(d.from||'Leader'),text:d.text,time:now()}); render(); toast(d.text||'New group message'); } relayPacket(p,event.endpointId); }
  async function listeners() { if (state.listeners || !plugin()) return; state.listeners=true; var p=plugin(); await p.addListener('meshState',function(e){state.running=Boolean(e.running);render();}); await p.addListener('peerFound',function(e){state.peers[e.endpointId]={name:e.displayName||'Nearby trekker',found:true,connected:false};render();}); await p.addListener('peerLost',function(e){delete state.peers[e.endpointId];render();}); await p.addListener('connectionChanged',function(e){state.peers[e.endpointId]=state.peers[e.endpointId]||{name:'Verified trekker'};state.peers[e.endpointId].connected=Boolean(e.connected);if(!e.connected)state.peerTest=null;render();}); await p.addListener('verificationRequired',function(e){ if(confirm('Nearby connection from '+(e.displayName||'a trekker')+'. Do the digits match on both phones?\n\n'+e.verificationCode+'\n\nAccept only after comparing in person.')) p.acceptConnection({endpointId:e.endpointId}); else p.rejectConnection({endpointId:e.endpointId}); }); await p.addListener('messageReceived',onPacket); await p.addListener('meshError',function(e){toast(e.message||e.type||'Trail Mesh error');}); }

  function bindUI(root) { root.querySelector('[data-rwm-close]').onclick=close; root.querySelectorAll('[data-rwm-tab]').forEach(function(x){x.onclick=function(){selectTab(x.dataset.rwmTab);};}); root.querySelector('#rwmName').value=safeName(); root.querySelector('#rwmStart').onclick=start; root.querySelector('#rwmStop').onclick=stop; root.querySelector('#rwmPing').onclick=networkTest; root.querySelector('#rwmRelay').checked=localStorage.getItem('rw_mesh_relay')==='1';state.relay=root.querySelector('#rwmRelay').checked;root.querySelector('#rwmRelay').onchange=function(e){state.relay=e.target.checked;localStorage.setItem('rw_mesh_relay',state.relay?'1':'0');toast(state.relay?'Three-hop lightweight relay enabled':'Relay disabled');}; root.querySelector('#rwmSend').onclick=function(){var x=root.querySelector('#rwmChatInput');sendChat(x.value).then(function(){x.value='';});}; root.querySelector('#rwmVoice').onclick=toggleVoice; root.querySelector('#rwmRadioCheck').onclick=radioCheck; root.querySelectorAll('[data-rwm-team]').forEach(function(x){x.onclick=function(){team(x.dataset.rwmTeam);};}); root.querySelectorAll('[data-rwm-fun]').forEach(function(x){x.onclick=function(){fun(x.dataset.rwmFun);};}); root.querySelector('#rwmLost').onclick=lost; root.querySelector('#rwmSOS').onclick=sos; root.querySelector('#rwmAlarm').onclick=function(){alarmCtx?stopAlarm():startAlarm();}; root.querySelector('#rwmOfficialSOS').onclick=function(){close();if(typeof window.openSOS==='function')window.openSOS();}; root.querySelector('#rwmShare').onclick=function(){shareFile(root.querySelector('#rwmFile').files[0]);}; }

  function installEntryPoints() {
    if (!plugin()) return; styles(); listeners();
    if (!document.getElementById('rwMeshFab')) { var f=document.createElement('button');f.id='rwMeshFab';f.textContent='📡';f.title='Open Trail Mesh';f.setAttribute('aria-label','Open Trail Mesh');f.onclick=function(){open();};document.body.appendChild(f); }
    var groupItem=Array.from(document.querySelectorAll('button,a,.drawer-item,.menu-item')).find(function(x){return /group chat/i.test(x.textContent||'');}); if(groupItem && !document.getElementById('rwMeshMenu')){var item=groupItem.cloneNode(true);item.id='rwMeshMenu';item.removeAttribute('onclick');item.innerHTML='📡 Trail Mesh <span class="rwm-badge">OFFLINE</span>';item.onclick=function(e){e.preventDefault();open();};groupItem.parentNode.insertBefore(item,groupItem.nextSibling);}
    var chat=document.querySelector('#groupChatOverlay,.group-chat-overlay,#tripChatOverlay'); if(chat && !chat.querySelector('.rwm-chat-launch')){var b=document.createElement('button');b.className='rwm-btn rwm-chat-launch';b.textContent='📡 Mesh';b.onclick=function(){open('chat');};chat.insertBefore(b,chat.firstChild);}
  }
  function installBridges() {
    var originalTrip=window.tripChatSend; if(typeof originalTrip==='function'&&!originalTrip.__rwm){var wrapped=function(){var input=document.getElementById('tripChatInput');var value=input&&input.value;var result=originalTrip.apply(this,arguments);if(state.running&&value)sendChat(value,'trip-chat').catch(function(){});return result;};wrapped.__rwm=true;window.tripChatSend=wrapped;}
    var originalTusk=window.copilotSend; if(typeof originalTusk==='function'&&!originalTusk.__rwm){var tusk=function(){var input=document.getElementById('cpInput')||document.getElementById('heroInput');var q=(input&&input.value||'').toLowerCase();if(/(open|start).*trail mesh|trail mesh.*(open|start)/.test(q)){open('connect');return;}if(/mesh status|nearby network test/.test(q)){open('connect');return;}if(/find.*(lost|missing).*trekker|lost trekker/.test(q)){open('team');return;}if(/(mesh|nearby).*sos|sos.*(mesh|nearby)/.test(q)){open('sos');return;}return originalTusk.apply(this,arguments);};tusk.__rwm=true;window.copilotSend=tusk;}
  }

  window.RWTrailMesh = { isAvailable:function(){return Boolean(plugin());}, open:open, close:close, start:start, stop:stop, send:function(message,endpointId){return requirePlugin().sendMessage({message:message,endpointId:endpointId||null});}, sendChat:sendChat, status:function(){return requirePlugin().getStatus();} };
  window.RWNearbyMesh = window.RWTrailMesh;
  function boot(){if(!plugin())return;installEntryPoints();installBridges();new MutationObserver(function(){installEntryPoints();installBridges();}).observe(document.body,{childList:true,subtree:true});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
