(function () {
  'use strict';

  var MAX_FILE_BYTES = 8 * 1024 * 1024;
  var CHUNK_BYTES = 8 * 1024;
  var state = { running: false, peers: {}, messages: [], transfers: {}, seen: {}, listeners: false, relay: false, recording: null, recorder: null };
  var deviceId = localStorage.getItem('rw_mesh_device_id') || id();
  localStorage.setItem('rw_mesh_device_id', deviceId);

  function plugin() { return window.Capacitor && window.Capacitor.Plugins && window.Capacitor.Plugins.NearbyMesh; }
  function esc(value) { var d = document.createElement('div'); d.textContent = String(value == null ? '' : value); return d.innerHTML; }
  function id() { return Date.now().toString(36) + Math.random().toString(36).slice(2, 8); }
  function now() { return new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); }
  function requirePlugin() { var p = plugin(); if (!p) throw new Error('Trail Mesh is available only in the RoamWise Android app.'); return p; }
  function packet(type, data) { var p={ rw: 1, type: type, id: id(), origin: deviceId, ttl: state.relay ? 3 : 0, at: Date.now(), data: data || {} }; state.seen[p.id]=p.at; return JSON.stringify(p); }
  function sendPacket(type, data, endpointId) { return requirePlugin().sendMessage({ message: packet(type, data), endpointId: endpointId || null }); }
  function relayPacket(p, sourceEndpoint) { if(!state.relay || !p.ttl || p.ttl<1 || p.origin===deviceId || /^(file-|ping$|pong$)/.test(p.type)) return; var relayed=JSON.stringify(Object.assign({},p,{ttl:p.ttl-1})); Object.keys(state.peers).forEach(function(key){if(key!==sourceEndpoint&&state.peers[key].connected)requirePlugin().sendMessage({message:relayed,endpointId:key}).catch(function(){});}); }
  function toast(message) { if (typeof window.showToast === 'function') window.showToast(message); else alert(message); }
  function formatBytes(n) { return n < 1024 * 1024 ? Math.ceil(n / 1024) + ' KB' : (n / 1024 / 1024).toFixed(1) + ' MB'; }
  function peerCount() { return Object.keys(state.peers).filter(function (key) { return state.peers[key].connected; }).length; }
  function safeName() { return (localStorage.getItem('rw_mesh_name') || localStorage.getItem('rw_user_name') || 'RoamWise trekker').slice(0, 32); }

  function styles() {
    if (document.getElementById('rwMeshStyles')) return;
    var s = document.createElement('style'); s.id = 'rwMeshStyles';
    s.textContent = '#rwMeshOverlay{position:fixed;inset:0;background:#07130ff2;z-index:2147483000;color:#f4fff9;font-family:system-ui;overflow:auto}' +
      '.rwm-shell{max-width:720px;margin:auto;min-height:100%;background:#0d1d17}.rwm-head{position:sticky;top:0;background:#10271eee;padding:16px;display:flex;align-items:center;gap:10px;z-index:2;border-bottom:1px solid #ffffff1c}' +
      '.rwm-head h2{margin:0;flex:1;font-size:20px}.rwm-close,.rwm-btn{border:0;border-radius:12px;padding:11px 14px;font-weight:700;background:#35d07f;color:#07130f}.rwm-btn.secondary{background:#203a30;color:#fff}.rwm-btn.danger{background:#ff5e62;color:#fff}' +
      '.rwm-tabs{display:flex;overflow:auto;padding:10px;gap:6px;background:#0d1d17;position:sticky;top:65px;z-index:2}.rwm-tab{white-space:nowrap;border:0;border-radius:18px;padding:9px 12px;background:#183128;color:#cce8dc}.rwm-tab.active{background:#35d07f;color:#07130f}' +
      '.rwm-body{padding:14px}.rwm-panel{display:none}.rwm-panel.active{display:block}.rwm-card{background:#142b22;border:1px solid #ffffff17;border-radius:16px;padding:14px;margin-bottom:12px}.rwm-card h3{margin:0 0 8px}.rwm-note{font-size:13px;color:#b7cfc5;line-height:1.45}.rwm-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.rwm-input{box-sizing:border-box;width:100%;background:#091710;border:1px solid #ffffff30;border-radius:12px;padding:12px;color:#fff;margin:7px 0}' +
      '.rwm-msg{padding:9px 11px;border-radius:12px;background:#1c392d;margin:7px 0}.rwm-msg.mine{background:#27553f;margin-left:12%}.rwm-meta{font-size:11px;color:#a7c2b7}.rwm-badge{font-size:11px;border-radius:10px;padding:3px 7px;background:#315344}.rwm-good{color:#5be498}.rwm-warn{color:#ffd166}.rwm-sos{border:1px solid #ff6b6b;background:#3b1c1e}.rwm-guide li{margin:8px 0;line-height:1.4}.rwm-progress{height:6px;background:#091710;border-radius:5px;overflow:hidden}.rwm-progress i{display:block;height:100%;background:#35d07f}' +
      '#rwMeshFab{position:fixed;right:16px;bottom:84px;z-index:99999;border:0;border-radius:24px;background:#173d30;color:#fff;padding:12px 15px;box-shadow:0 4px 20px #0008}.rwm-alarm{animation:rwmPulse .7s infinite alternate}@keyframes rwmPulse{to{background:#f00}}';
    document.head.appendChild(s);
  }

  function template() {
    return '<div class="rwm-shell"><div class="rwm-head"><span>📡</span><h2>Trail Mesh</h2><span id="rwmStatus" class="rwm-badge">Stopped</span><button class="rwm-close" data-rwm-close>✕</button></div>' +
      '<div class="rwm-tabs">' + ['Connect','Chat','Team','SOS','Share','Fun','Guide'].map(function (x, i) { return '<button class="rwm-tab '+(i?'':'active')+'" data-rwm-tab="'+x.toLowerCase()+'">'+x+'</button>'; }).join('') + '</div><div class="rwm-body">' +
      '<section class="rwm-panel active" data-rwm-panel="connect"><div class="rwm-card"><h3>Nearby, offline coordination</h3><p class="rwm-note">Uses Bluetooth and nearby Wi-Fi radios. Internet and mobile service are not required, but devices must remain within local radio range. It is not satellite rescue or guaranteed emergency delivery.</p><input id="rwmName" class="rwm-input" maxlength="32" placeholder="Trail display name"><div class="rwm-row"><button id="rwmStart" class="rwm-btn">Allow & start</button><button id="rwmStop" class="rwm-btn secondary">Stop</button><button id="rwmPing" class="rwm-btn secondary">Test network</button></div></div><div class="rwm-card"><h3>Multi-hop relay (experimental)</h3><label><input id="rwmRelay" type="checkbox"> Relay text, team, lost-trekker and SOS alerts through verified phones</label><p class="rwm-note">Opt-in on each phone. Maximum three hops; duplicate IDs and expiry prevent loops. Files, songs, videos and voice notes are never relayed because they can congest an emergency network. Relay confirms forwarding—not rescue delivery.</p></div><div class="rwm-card"><h3>Nearby trekkers <span id="rwmPeerCount" class="rwm-badge">0</span></h3><div id="rwmPeers" class="rwm-note">No connected trekkers yet.</div></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="chat"><div class="rwm-card"><h3>Offline Trip Chat & radio room</h3><p class="rwm-note">Messages are shared with verified connected devices and can appear in Trip Chat. Voice is push-to-talk: record, release and share. This remains usable under weak links where live conferencing would break.</p><div id="rwmMessages"></div><textarea id="rwmChatInput" class="rwm-input" rows="2" maxlength="4000" placeholder="Message your nearby team"></textarea><div class="rwm-row"><button id="rwmSend" class="rwm-btn">Send offline</button><button id="rwmVoice" class="rwm-btn secondary">🎙 Hold radio note</button><button id="rwmRadioCheck" class="rwm-btn secondary">Radio check</button></div></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="team"><div class="rwm-card"><h3>Trek leader coordination</h3><input id="rwmCheckpoint" class="rwm-input" maxlength="120" placeholder="Checkpoint or meeting place"><div class="rwm-row"><button class="rwm-btn" data-rwm-team="rollcall">Roll call</button><button class="rwm-btn secondary" data-rwm-team="regroup">Regroup</button><button class="rwm-btn secondary" data-rwm-team="hold">Hold position</button></div></div><div class="rwm-card"><h3>Find a lost trekker</h3><p class="rwm-note">Broadcasts an alert locally. The missing person becomes discoverable only when their phone is running Trail Mesh and enters radio range.</p><input id="rwmLostName" class="rwm-input" maxlength="80" placeholder="Name / description"><button id="rwmLost" class="rwm-btn danger">Broadcast lost-trekker alert</button></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="sos"><div class="rwm-card rwm-sos"><h3>Emergency help</h3><p class="rwm-note">If mobile service exists, contact local emergency services first. Trail Mesh only alerts nearby connected users and delivery is not guaranteed.</p><select id="rwmSosType" class="rwm-input"><option>Medical emergency</option><option>Lost / separated</option><option>Unsafe situation</option><option>Need supplies or assistance</option></select><input id="rwmSosDetails" class="rwm-input" maxlength="240" placeholder="Details, clothing, direction, injury"><div class="rwm-row"><button id="rwmSOS" class="rwm-btn danger">Broadcast nearby SOS</button><button id="rwmAlarm" class="rwm-btn secondary">Sound local alarm</button><button id="rwmOfficialSOS" class="rwm-btn secondary">Open RoamWise SOS</button></div></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="share"><div class="rwm-card"><h3>Share without internet</h3><p class="rwm-note">Send a photo, short video, voice note, document, or song up to 8 MB to directly connected teammates. Keep the app open and devices nearby until complete.</p><input id="rwmFile" type="file" class="rwm-input" accept="image/*,video/*,audio/*,.pdf,.txt"><button id="rwmShare" class="rwm-btn">Share selected file</button><div id="rwmTransfers"></div></div></section>' +
      '<section class="rwm-panel" data-rwm-panel="fun"><div class="rwm-card"><h3>Trail fun</h3><p class="rwm-note">Lightweight activities designed not to flood the radio. Shared music and videos still use the Share tab.</p><div class="rwm-row"><button class="rwm-btn" data-rwm-fun="photo">📷 Photo challenge</button><button class="rwm-btn secondary" data-rwm-fun="story">🔥 Campfire story</button><button class="rwm-btn secondary" data-rwm-fun="quiz">🧭 Trail quiz</button><button class="rwm-btn secondary" data-rwm-fun="cheer">🙌 Team cheer</button></div></div></section>' +
      '<section class="rwm-panel rwm-guide" data-rwm-panel="guide"><div class="rwm-card"><h3>Quick tutorial</h3><ol><li>Open Trail Mesh on every Android phone and tap <b>Allow & start</b>.</li><li>Keep Bluetooth, Wi-Fi and location services enabled. Android may require Nearby Devices and location permissions.</li><li>Compare the verification digits shown on both phones in person. Accept only when they match.</li><li>Use Offline Trip Chat, Team, Share, Fun, or SOS. Keep phones nearby and the app open during transfers.</li><li>Enable relay only when the group agrees; distribute relay phones along the route.</li><li>Tap Stop when the trek ends to stop discovery and advertising.</li></ol></div><div class="rwm-card"><h3>Safety & privacy</h3><ul><li>Your chosen trail name is visible to nearby Trail Mesh users while running.</li><li>Never accept an unexpected verification request.</li><li>Range varies with terrain, bodies, weather, and hardware. Relay is limited to three hops and lightweight alerts.</li><li>Voice uses recorded push-to-talk notes; it is not a guaranteed full-duplex phone call.</li><li>Use official emergency channels whenever available. Do not rely on Trail Mesh as your only safety plan.</li></ul></div><div class="rwm-card"><h3>Ailon Tusk shortcuts</h3><p class="rwm-note">Try: “open Trail Mesh”, “mesh status”, “find lost trekker”, or “nearby SOS”. Tusk opens the matching control while you confirm every safety-sensitive broadcast.</p></div></section></div></div>';
  }

  function open(tab) {
    styles(); var overlay = document.getElementById('rwMeshOverlay');
    if (!overlay) { overlay = document.createElement('div'); overlay.id = 'rwMeshOverlay'; overlay.innerHTML = template(); document.body.appendChild(overlay); bindUI(overlay); }
    overlay.style.display = 'block'; document.body.style.overflow = 'hidden'; selectTab(tab || 'connect'); render();
  }
  function close() { var o = document.getElementById('rwMeshOverlay'); if (o) o.style.display = 'none'; document.body.style.overflow = ''; stopAlarm(); }
  function selectTab(name) { document.querySelectorAll('[data-rwm-tab]').forEach(function (x) { x.classList.toggle('active', x.dataset.rwmTab === name); }); document.querySelectorAll('[data-rwm-panel]').forEach(function (x) { x.classList.toggle('active', x.dataset.rwmPanel === name); }); }
  function render() {
    var status = document.getElementById('rwmStatus'); if (status) { status.textContent = state.running ? 'Running · ' + peerCount() + ' connected' : 'Stopped'; status.className = 'rwm-badge ' + (state.running ? 'rwm-good' : ''); }
    var pc = document.getElementById('rwmPeerCount'); if (pc) pc.textContent = String(peerCount());
    var peers = document.getElementById('rwmPeers'); if (peers) { var list = Object.keys(state.peers).map(function (key) { var p = state.peers[key]; return '<div class="rwm-msg"><b>'+esc(p.name || 'Nearby trekker')+'</b><div class="rwm-meta">'+esc(p.connected ? 'Connected and verified' : p.found ? 'Discovered' : 'Disconnected')+'</div></div>'; }); peers.innerHTML = list.join('') || 'No connected trekkers yet.'; }
    var messages = document.getElementById('rwmMessages'); if (messages) { messages.innerHTML = state.messages.slice(-100).map(function (m) { return '<div class="rwm-msg '+(m.mine?'mine':'')+'"><b>'+esc(m.from)+'</b> '+esc(m.text)+'<div class="rwm-meta">'+esc(m.time)+'</div></div>'; }).join('') || '<p class="rwm-note">No offline messages yet.</p>'; messages.scrollTop = messages.scrollHeight; }
  }

  async function start() { try { var name = document.getElementById('rwmName').value.trim() || safeName(); localStorage.setItem('rw_mesh_name', name); await requirePlugin().requestMeshPermissions(); await requirePlugin().start({ displayName: name }); state.running = true; render(); toast('Trail Mesh is running nearby'); } catch (e) { toast(e.message || 'Could not start Trail Mesh'); } }
  async function stop() { try { await requirePlugin().stop(); state.running = false; state.peers = {}; render(); toast('Trail Mesh stopped'); } catch (e) { toast(e.message || 'Could not stop Trail Mesh'); } }
  async function sendChat(text, source) { text = String(text || '').trim(); if (!text) return; await sendPacket('chat', { text: text, source: source || 'mesh', from: safeName() }); state.messages.push({ mine: true, from: 'You', text: text, time: now() }); render(); }
  function mirrorToTripChat(message) { var box = document.querySelector('#groupChatMessages,.group-chat-messages,#tripChatMessages'); if (!box) return; var row = document.createElement('div'); row.className = 'chat-message mesh-message'; row.innerHTML = '<b>📡 '+esc(message.from || 'Nearby trekker')+'</b><div>'+esc(message.text)+'</div><small>Offline Trail Mesh · '+esc(now())+'</small>'; box.appendChild(row); }

  async function networkTest() { if (!state.running) return toast('Start Trail Mesh first'); if (!peerCount()) return toast('Connect and verify another phone first'); var testId = id(); state.transfers['ping:'+testId] = Date.now(); await sendPacket('ping', { testId: testId, from: safeName() }); toast('Test message sent'); }
  async function radioCheck() { await sendPacket('team',{action:'radio-check',text:'Radio check — reply SAFE with your name and position',from:safeName()}); state.messages.push({mine:true,from:'Radio room',text:'Radio check sent',time:now()}); render(); }
  async function fun(kind) { var prompts={photo:'Photo challenge: capture the best trail view in 10 minutes 📷',story:'Campfire round: share a two-minute travel story 🔥',quiz:'Trail quiz: leader, send the next nature or navigation question 🧭',cheer:'Team cheer from '+safeName()+' 🙌'}; await sendPacket('fun',{kind:kind,text:prompts[kind],from:safeName()}); state.messages.push({mine:true,from:'Trail fun',text:prompts[kind],time:now()}); render(); }
  async function team(kind) { var cp = (document.getElementById('rwmCheckpoint').value || '').trim(); var labels = { rollcall: 'Roll call: reply that you are safe', regroup: 'Regroup' + (cp ? ' at '+cp : ' at the agreed checkpoint'), hold: 'Hold position and wait for the leader' }; await sendPacket('team', { action: kind, text: labels[kind], from: safeName() }); state.messages.push({ mine: true, from: 'Team command', text: labels[kind], time: now() }); render(); toast('Team command broadcast nearby'); }
  async function lost() { var name = document.getElementById('rwmLostName').value.trim(); if (!name) return toast('Add the lost trekker’s name or description'); if (!confirm('Broadcast this lost-trekker alert to all connected nearby devices?')) return; await sendPacket('lost', { person: name, from: safeName() }); toast('Lost-trekker alert broadcast nearby'); }
  async function getLocation() { try { var pos = await new Promise(function (resolve, reject) { navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 10000 }); }); return { lat: +pos.coords.latitude.toFixed(6), lng: +pos.coords.longitude.toFixed(6), accuracy: Math.round(pos.coords.accuracy) }; } catch (_) { return null; } }
  async function sos() { var type = document.getElementById('rwmSosType').value, details = document.getElementById('rwmSosDetails').value.trim(); if (!confirm('Broadcast a nearby SOS? Delivery is not guaranteed. Contact emergency services when possible.')) return; var location = await getLocation(); await sendPacket('sos', { emergency: type, details: details, location: location, from: safeName() }); startAlarm(); toast('SOS broadcast to connected nearby devices'); }
  var alarmCtx;
  function startAlarm() { stopAlarm(); var b = document.getElementById('rwmAlarm'); if (b) { b.classList.add('rwm-alarm'); b.textContent = 'Stop alarm'; } try { alarmCtx = new (window.AudioContext || window.webkitAudioContext)(); var o = alarmCtx.createOscillator(), g = alarmCtx.createGain(); o.frequency.value = 880; g.gain.value = .2; o.connect(g); g.connect(alarmCtx.destination); o.start(); alarmCtx.oscillator = o; } catch (_) {} if (navigator.vibrate) navigator.vibrate([500,250,500,250,1000]); }
  function stopAlarm() { if (alarmCtx) { try { alarmCtx.close(); } catch (_) {} alarmCtx = null; } if (navigator.vibrate) navigator.vibrate(0); var b = document.getElementById('rwmAlarm'); if (b) { b.classList.remove('rwm-alarm'); b.textContent = 'Sound local alarm'; } }

  function bytesToBase64(bytes) { var out = ''; for (var i=0;i<bytes.length;i++) out += String.fromCharCode(bytes[i]); return btoa(out); }
  function base64ToBytes(value) { var raw = atob(value), out = new Uint8Array(raw.length); for (var i=0;i<raw.length;i++) out[i] = raw.charCodeAt(i); return out; }
  async function shareFile(file) { if (!file) return toast('Choose a file first'); if (file.size > MAX_FILE_BYTES) return toast('Choose a file smaller than 8 MB'); if (!state.running || !peerCount()) return toast('Start Trail Mesh and connect a verified device first'); var transferId = id(), total = Math.ceil(file.size / CHUNK_BYTES); await sendPacket('file-start', { transferId: transferId, name: file.name, mime: file.type || 'application/octet-stream', size: file.size, total: total }); for (var i=0;i<total;i++) { var bytes = new Uint8Array(await file.slice(i*CHUNK_BYTES, (i+1)*CHUNK_BYTES).arrayBuffer()); await sendPacket('file-chunk', { transferId: transferId, index: i, value: bytesToBase64(bytes) }); updateTransfer('Sending '+file.name, (i+1)/total); } await sendPacket('file-end', { transferId: transferId }); toast('Shared '+file.name+' nearby'); }
  function updateTransfer(label, ratio, link) { var el = document.getElementById('rwmTransfers'); if (!el) return; el.innerHTML = '<div class="rwm-card"><div>'+esc(label)+'</div><div class="rwm-progress"><i style="width:'+Math.round(ratio*100)+'%"></i></div>'+(link || '')+'</div>' + el.innerHTML; }
  function receiveFile(p) { var d = p.data || {}, t = state.transfers[d.transferId]; if (p.type === 'file-start') { state.transfers[d.transferId] = { name: d.name, mime: d.mime, size: d.size, total: d.total, chunks: [] }; updateTransfer('Receiving '+d.name, 0); } else if (p.type === 'file-chunk' && t) { t.chunks[d.index] = base64ToBytes(d.value); updateTransfer('Receiving '+t.name, t.chunks.filter(Boolean).length/t.total); } else if (p.type === 'file-end' && t && t.chunks.filter(Boolean).length === t.total) { var url = URL.createObjectURL(new Blob(t.chunks, { type: t.mime })); updateTransfer('Received '+t.name+' · '+formatBytes(t.size), 1, '<p><a class="rwm-btn" download="'+esc(t.name)+'" href="'+url+'">Open / save</a></p>'); delete state.transfers[d.transferId]; toast('Received '+t.name); } }
  async function toggleVoice() { if (state.recorder && state.recorder.state === 'recording') { state.recorder.stop(); return; } try { var stream = await navigator.mediaDevices.getUserMedia({ audio: true }), chunks = []; state.recorder = new MediaRecorder(stream); state.recorder.ondataavailable = function (e) { if (e.data.size) chunks.push(e.data); }; state.recorder.onstop = function () { stream.getTracks().forEach(function (x) { x.stop(); }); var blob = new Blob(chunks, { type: state.recorder.mimeType || 'audio/webm' }); shareFile(new File([blob], 'trail-voice-'+Date.now()+'.webm', { type: blob.type })); state.recorder = null; var b=document.getElementById('rwmVoice'); if(b)b.textContent='🎙 Record voice note'; }; state.recorder.start(); var btn=document.getElementById('rwmVoice'); if(btn)btn.textContent='⏹ Send voice note'; setTimeout(function(){ if(state.recorder && state.recorder.state==='recording')state.recorder.stop(); },60000); } catch (e) { toast('Microphone access is required for voice notes'); } }

  function onPacket(event) { var p; try { p = JSON.parse(event.message); } catch (_) { p = { type:'chat', data:{ text:event.message, from:event.endpointName } }; } if (!p || p.rw !== 1 && p.type !== 'chat') return; if(p.id&&state.seen[p.id])return; if(p.id){state.seen[p.id]=Date.now();Object.keys(state.seen).forEach(function(key){if(Date.now()-state.seen[key]>600000)delete state.seen[key];});} var d=p.data||{}; if (p.type==='chat') { var m={ mine:false, from:d.from||event.endpointName||'Nearby trekker', text:d.text||'', time:now() }; state.messages.push(m); mirrorToTripChat(m); toast('Offline message from '+m.from); render(); } else if (p.type==='ping') { sendPacket('pong',{testId:d.testId,from:safeName()},event.endpointId); } else if (p.type==='pong') { var sent=state.transfers['ping:'+d.testId]; if(sent){ toast('Network test passed in '+(Date.now()-sent)+' ms'); delete state.transfers['ping:'+d.testId]; } } else if (p.type.indexOf('file-')===0) receiveFile(p); else if (p.type==='sos') { startAlarm(); open('sos'); toast('Nearby SOS from '+(d.from||'a trekker')+': '+(d.emergency||'Help needed')); } else if (p.type==='lost') { open('team'); toast('Lost-trekker alert: '+(d.person||'unknown person')); } else if (p.type==='team'||p.type==='fun') { state.messages.push({mine:false,from:(p.type==='fun'?'Trail fun':'Team')+' · '+(d.from||'Leader'),text:d.text,time:now()}); render(); toast(d.text||'New group message'); } relayPacket(p,event.endpointId); }
  async function listeners() { if (state.listeners || !plugin()) return; state.listeners=true; var p=plugin(); await p.addListener('meshState',function(e){state.running=Boolean(e.running);render();}); await p.addListener('peerFound',function(e){state.peers[e.endpointId]={name:e.endpointName,found:true,connected:false};render();}); await p.addListener('peerLost',function(e){delete state.peers[e.endpointId];render();}); await p.addListener('connectionChanged',function(e){state.peers[e.endpointId]=state.peers[e.endpointId]||{};state.peers[e.endpointId].name=e.endpointName||state.peers[e.endpointId].name;state.peers[e.endpointId].connected=e.status==='connected';render();}); await p.addListener('verificationRequired',function(e){ if(confirm('Nearby connection from '+(e.endpointName||'a trekker')+'. Do the digits match on both phones?\n\n'+e.verificationCode+'\n\nAccept only after comparing in person.')) p.acceptConnection({endpointId:e.endpointId}); else p.rejectConnection({endpointId:e.endpointId}); }); await p.addListener('messageReceived',onPacket); await p.addListener('meshError',function(e){toast(e.message||'Trail Mesh error');}); }

  function bindUI(root) { root.querySelector('[data-rwm-close]').onclick=close; root.querySelectorAll('[data-rwm-tab]').forEach(function(x){x.onclick=function(){selectTab(x.dataset.rwmTab);};}); root.querySelector('#rwmName').value=safeName(); root.querySelector('#rwmStart').onclick=start; root.querySelector('#rwmStop').onclick=stop; root.querySelector('#rwmPing').onclick=networkTest; root.querySelector('#rwmRelay').checked=localStorage.getItem('rw_mesh_relay')==='1';state.relay=root.querySelector('#rwmRelay').checked;root.querySelector('#rwmRelay').onchange=function(e){state.relay=e.target.checked;localStorage.setItem('rw_mesh_relay',state.relay?'1':'0');toast(state.relay?'Three-hop lightweight relay enabled':'Relay disabled');}; root.querySelector('#rwmSend').onclick=function(){var x=root.querySelector('#rwmChatInput');sendChat(x.value).then(function(){x.value='';});}; root.querySelector('#rwmVoice').onclick=toggleVoice; root.querySelector('#rwmRadioCheck').onclick=radioCheck; root.querySelectorAll('[data-rwm-team]').forEach(function(x){x.onclick=function(){team(x.dataset.rwmTeam);};}); root.querySelectorAll('[data-rwm-fun]').forEach(function(x){x.onclick=function(){fun(x.dataset.rwmFun);};}); root.querySelector('#rwmLost').onclick=lost; root.querySelector('#rwmSOS').onclick=sos; root.querySelector('#rwmAlarm').onclick=function(){alarmCtx?stopAlarm():startAlarm();}; root.querySelector('#rwmOfficialSOS').onclick=function(){close();if(typeof window.openSOS==='function')window.openSOS();}; root.querySelector('#rwmShare').onclick=function(){shareFile(root.querySelector('#rwmFile').files[0]);}; }

  function installEntryPoints() {
    if (!plugin()) return; styles(); listeners();
    if (!document.getElementById('rwMeshFab')) { var f=document.createElement('button');f.id='rwMeshFab';f.textContent='📡 Trail Mesh';f.onclick=function(){open();};document.body.appendChild(f); }
    var groupItem=Array.from(document.querySelectorAll('button,a,.drawer-item,.menu-item')).find(function(x){return /group chat/i.test(x.textContent||'');}); if(groupItem && !document.getElementById('rwMeshMenu')){var item=groupItem.cloneNode(true);item.id='rwMeshMenu';item.removeAttribute('onclick');item.innerHTML='📡 Trail Mesh <span class="rwm-badge">OFFLINE</span>';item.onclick=function(e){e.preventDefault();open();};groupItem.parentNode.insertBefore(item,groupItem.nextSibling);}
    var chat=document.querySelector('#groupChatOverlay,.group-chat-overlay,#tripChatOverlay'); if(chat && !chat.querySelector('.rwm-chat-launch')){var b=document.createElement('button');b.className='rwm-btn rwm-chat-launch';b.textContent='📡 Mesh';b.onclick=function(){open('chat');};chat.insertBefore(b,chat.firstChild);}
  }
  function installBridges() {
    var originalTrip=window.tripChatSend; if(typeof originalTrip==='function'&&!originalTrip.__rwm){var wrapped=function(){var input=document.getElementById('tripChatInput');var value=input&&input.value;var result=originalTrip.apply(this,arguments);if(state.running&&value)sendChat(value,'trip-chat').catch(function(){});return result;};wrapped.__rwm=true;window.tripChatSend=wrapped;}
    var originalTusk=window.copilotSend; if(typeof originalTusk==='function'&&!originalTusk.__rwm){var tusk=function(){var input=document.getElementById('cpInput')||document.getElementById('heroInput');var q=(input&&input.value||'').toLowerCase();if(/(open|start).*trail mesh|trail mesh.*(open|start)/.test(q)){open('connect');return;}if(/mesh status|nearby network test/.test(q)){open('connect');return;}if(/find.*(lost|missing).*trekker|lost trekker/.test(q)){open('team');return;}if(/(mesh|nearby).*sos|sos.*(mesh|nearby)/.test(q)){open('sos');return;}return originalTusk.apply(this,arguments);};tusk.__rwm=true;window.copilotSend=tusk;}
  }

  window.RWTrailMesh = { isAvailable:function(){return Boolean(plugin());}, open:open, close:close, start:start, stop:stop, send:function(message,endpointId){return requirePlugin().sendMessage({message:message,endpointId:endpointId||null});}, sendChat:sendChat, status:function(){return requirePlugin().getStatus();} };
  window.RWNearbyMesh = window.RWTrailMesh;
  function boot(){if(!plugin())return;installEntryPoints();installBridges();new MutationObserver(function(){installEntryPoints();installBridges();}).observe(document.body,{childList:true,subtree:true});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
